### PR TITLE
Update deploy-enterprise.yml to decrease lifecycle for some of JPL accounts

### PR DESCRIPTION
**Pull request by cmarshak**
Thanks, Andrew and Joe, with your help with this, i.e. telling me what to do.

### CODE REVIEW

**Review by jhkennedy — APPROVED** [review]

**Comment by jhkennedy** [comment]
:thinking: I'm not sure why the test actions aren't running for this PR

**Comment by cmarshak** [comment]
I actually made a PR first into my own develop branch and then closed that. Maybe I should make a new commit? I will make one of them 13 days ;)

**Comment by jhkennedy** [comment]
Ah, everything is `on: push` so runs in the fork's actions space -- need to add `on: pr` to them to see them here as well.

**Comment by cmarshak** [comment]
I will leave at 13 days - no biggie

**Review by jhkennedy — APPROVED** [review]

**Pull request merged**
